import { z } from "zod";

export const cocktailSchema = z.object({
  idDrink: z.string(),
  strDrink: z.string().nullish(),
  strDrinkAlternate: z.string().nullish(),
  strTags: z.string().nullish(),
  strVideo: z.string().nullish(),
  strCategory: z.string().nullish(),
  strIBA: z.string().nullish(),
  strAlcoholic: z.string().nullish(),
  strGlass: z.string().nullish(),
  strInstructions: z.string().nullish(),
  strInstructionsES: z.string().nullish(),
  strInstructionsDE: z.string().nullish(),
  strInstructionsFR: z.string().nullish(),
  strInstructionsIT: z.string().nullish(),
  "strInstructionsZH-HANS": z.string().nullish(),
  "strInstructionsZH-HANT": z.string().nullish(),
  strDrinkThumb: z.string().url().nullish(),
  strIngredient1: z.string().nullish(),
  strIngredient2: z.string().nullish(),
  strIngredient3: z.string().nullish(),
  strIngredient4: z.string().nullish(),
  strIngredient5: z.string().nullish(),
  strIngredient6: z.string().nullish(),
  strIngredient7: z.string().nullish(),
  strIngredient8: z.string().nullish(),
  strIngredient9: z.string().nullish(),
  strIngredient10: z.string().nullish(),
  strIngredient11: z.string().nullish(),
  strIngredient12: z.string().nullish(),
  strIngredient13: z.string().nullish(),
  strIngredient14: z.string().nullish(),
  strIngredient15: z.string().nullish(),
  strMeasure1: z.string().nullish(),
  strMeasure2: z.string().nullish(),
  strMeasure3: z.string().nullish(),
  strMeasure4: z.string().nullish(),
  strMeasure5: z.string().nullish(),
  strMeasure6: z.string().nullish(),
  strMeasure7: z.string().nullish(),
  strMeasure8: z.string().nullish(),
  strMeasure9: z.string().nullish(),
  strMeasure10: z.string().nullish(),
  strMeasure11: z.string().nullish(),
  strMeasure12: z.string().nullish(),
  strMeasure13: z.string().nullish(),
  strMeasure14: z.string().nullish(),
  strMeasure15: z.string().nullish(),
  strImageSource: z.string().nullish(),
  strImageAttribution: z.string().nullish(),
  strCreativeCommonsConfirmed: z.string().nullish(),
  dateModified: z
    .string()
    .refine((date) => !isNaN(Date.parse(date)), {
      message: "Invalid date format",
    })
    .nullish(),
});

export const cocktailApiResponseSchema = z.object({
  drinks: z.array(cocktailSchema),
});
